/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    socials: Social;
    projects: Project;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug?: string | null;
  isMasthead?: boolean | null;
  feature?: ('none' | 'slider' | 'banner') | null;
  mastheadSlider?: {
    slides?:
      | {
          media: string | Media;
          heading?: string | null;
          copy?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          attribution?: string | null;
          button: {
            text: string;
            url: string;
            target?: ('_self' | '_blank' | '_parent' | '_top') | null;
            ariaLabel?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    settings?: {
      desktop?: {
        dots?: boolean | null;
        loop?: boolean | null;
        arrows?: boolean | null;
        draggable?: boolean | null;
        autoplay?: boolean | null;
        autoplaySpeed?: number | null;
        slidesPerRow?: number | null;
      };
      mobile?: {
        dots?: boolean | null;
        loop?: boolean | null;
        arrows?: boolean | null;
        draggable?: boolean | null;
        autoplay?: boolean | null;
        autoplaySpeed?: number | null;
        slidesPerRow?: number | null;
      };
    };
  };
  customComponents?:
    | (
        | {
            copy: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'WYSIWYG';
          }
        | {
            author: string;
            quote: string;
            decoration?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Quote';
          }
        | {
            heading?: string | null;
            level?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5') | null;
            copy?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'HeadingCopy';
          }
        | {
            heading?: string | null;
            level?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Heading';
          }
        | {
            slides?:
              | {
                  media: string | Media;
                  heading?: string | null;
                  copy?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  attribution?: string | null;
                  button: {
                    text: string;
                    url: string;
                    target?: ('_self' | '_blank' | '_parent' | '_top') | null;
                    ariaLabel?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            desktop?: {
              dots?: boolean | null;
              loop?: boolean | null;
              arrows?: boolean | null;
              draggable?: boolean | null;
              autoplay?: boolean | null;
              autoplaySpeed?: number | null;
              slidesPerRow?: number | null;
            };
            mobile?: {
              dots?: boolean | null;
              loop?: boolean | null;
              arrows?: boolean | null;
              draggable?: boolean | null;
              autoplay?: boolean | null;
              autoplaySpeed?: number | null;
              slidesPerRow?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'Slider';
          }
      )[]
    | null;
  subpages?: (string | Page)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: string;
  name?: ('linkedin' | 'github' | 'stackoverflow') | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name?: string | null;
  description?: string | null;
  media?: (string | null) | Media;
  mediaUrl?: string | null;
  buttons?:
    | {
        button: {
          text: string;
          url: string;
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'socials';
        value: string | Social;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  isMasthead?: T;
  feature?: T;
  mastheadSlider?:
    | T
    | {
        slides?:
          | T
          | {
              media?: T;
              heading?: T;
              copy?: T;
              attribution?: T;
              button?:
                | T
                | {
                    text?: T;
                    url?: T;
                    target?: T;
                    ariaLabel?: T;
                  };
              id?: T;
            };
        settings?:
          | T
          | {
              desktop?:
                | T
                | {
                    dots?: T;
                    loop?: T;
                    arrows?: T;
                    draggable?: T;
                    autoplay?: T;
                    autoplaySpeed?: T;
                    slidesPerRow?: T;
                  };
              mobile?:
                | T
                | {
                    dots?: T;
                    loop?: T;
                    arrows?: T;
                    draggable?: T;
                    autoplay?: T;
                    autoplaySpeed?: T;
                    slidesPerRow?: T;
                  };
            };
      };
  customComponents?:
    | T
    | {
        WYSIWYG?:
          | T
          | {
              copy?: T;
              id?: T;
              blockName?: T;
            };
        Quote?:
          | T
          | {
              author?: T;
              quote?: T;
              decoration?: T;
              id?: T;
              blockName?: T;
            };
        HeadingCopy?:
          | T
          | {
              heading?: T;
              level?: T;
              copy?: T;
              id?: T;
              blockName?: T;
            };
        Heading?:
          | T
          | {
              heading?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        Slider?:
          | T
          | {
              slides?:
                | T
                | {
                    media?: T;
                    heading?: T;
                    copy?: T;
                    attribution?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          url?: T;
                          target?: T;
                          ariaLabel?: T;
                        };
                    id?: T;
                  };
              desktop?:
                | T
                | {
                    dots?: T;
                    loop?: T;
                    arrows?: T;
                    draggable?: T;
                    autoplay?: T;
                    autoplaySpeed?: T;
                    slidesPerRow?: T;
                  };
              mobile?:
                | T
                | {
                    dots?: T;
                    loop?: T;
                    arrows?: T;
                    draggable?: T;
                    autoplay?: T;
                    autoplaySpeed?: T;
                    slidesPerRow?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  subpages?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  media?: T;
  mediaUrl?: T;
  buttons?:
    | T
    | {
        button?:
          | T
          | {
              text?: T;
              url?: T;
              target?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}